### ISSUE TITLE
Drink from rivers

### ISSUE THREAD

**Issue by NathanSalapat** [bendeutsch/minetest-thirsty#1]
Would you consider adding the ability to drink from rivers. I don't feel like forking to add these two lines to the config.lua file.

```
    ['default:river_water_source'] = true,
    ['default:river_water_flowing'] = true,
```

Now that rivers have been added to default game I think people will want to be able to drink from rivers as well. Unless you want to consider one water source potable and the other not, but then I would think that river water should be safe and sea water not.

**Comment by bendeutsch** [comment]
Thanks for the heads-up! I'll put it in right now.

**Comment by bendeutsch** [comment]
Done in version 0.8.1
