### ISSUE TITLE
thirsty.drink error

### ISSUE THREAD

**Issue by NathanSalapat** [bendeutsch/minetest-thirsty#3]
19:14:07: ACTION[ServerThread]: singleplayer uses food:apple, pointing at [nothing]
19:14:07: ERROR[main]: ServerError: ...athan/.minetest/games/Survive/mods/thirsty/functions.lua:57: attempt to call method 'get_player_name' (a nil value)
19:14:07: ERROR[main]: stack traceback:
19:14:07: ERROR[main]:  ...athan/.minetest/games/Survive/mods/thirsty/functions.lua:57: in function 'drink'

no ideas on this one. :(

**Comment by bendeutsch** [comment]
See my posts in the Minetest forums; I'm guessing you're not passing the correct `player` parameter to `thirsty.drink`. The following works for me, for example:

``` lua
minetest.override_item('default:apple', {
    on_use = function(itemstack, user, pointed_thing)
        thirsty.drink(user, 2, 20)
        local eat_func = minetest.item_eat(1)
        return eat_func(itemstack, user, pointed_thing)
    end
}) 
```
